layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: angelo.giacco.7121
  # hackerrank: your_username
  instagram: angelosgiacco
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: giaccoangelo
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Swift
    image_url: https://www.google.com/imgres?imgurl=https%3A%2F%2Fdeveloper.apple.com%2Fswift%2Fimages%2Fswift-og.png&imgrefurl=https%3A%2F%2Fdeveloper.apple.com%2Fswift%2F&docid=u-20sgoUCTYNfM&tbnid=HSdVeE9a2L7euM%3A&vet=10ahUKEwi5xu_m0L7hAhXUUBUIHQETBi4QMwhBKAAwAA..i&w=1200&h=1200&bih=821&biw=1440&q=swift%20programming%20language%20logo&ved=0ahUKEwi5xu_m0L7hAhXUUBUIHQETBi4QMwhBKAAwAA&iact=mrc&uact=8

  - name: Keras
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c9/Keras_Logo.jpg

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png


 
