layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects: pyhoneybot
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: angelo.giacco.7121
  # hackerrank: your_username
  instagram: angelosgiacco
  # keybase: your_username
  linkedin: angelo-giacco-450b2017a
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: giaccoangelo
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Swift
    image_url: http://static1.squarespace.com/static/558def25e4b0fc259f066636/5a49786bf9619ae3bb6a2564/5b68eeacaa4a99da3bcdc610/1545107487365/Swift_logo.png
  
  - name: Keras
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c9/Keras_Logo.jpg

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
